# Site settings
title: Code Notes, the code snippet manager for developers
email: thiebault.laurent@gmail.com
description: A simple code snippet manager for developers built with Electron & Vue.js ðŸš€

baseurl: ""
url: "https://food-limit.github.io"

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
#data-ad-slot: 0123456789
#data-ad-client: ca-pub-ABCD
# google_ad_client: ca-pub-7380281265540998

google_analytics: "UA-113243461-1"
#addthis_id: ra-xxxxxxxxxxxx
#disqus_account: xxxxxx

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: github
    url: http://github.com/lauthieb/code-notes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","gulpfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]
